export enum NavigationLinks {
    home = "/home",
    calendar = "/calendar",
    promotionsList = "/promotion/list",
    promotionCards = "/promotion/cards",
    promotionDetails = "/promotion/details",
    promotionEdit = "/promotion/edit",
    promotionCopy = "/promotion/copy",
    forecastEdit = "promotion/forecast/edit",
    forecastDetails = "promotion/forecast/details",
    participantAttributes = "promotion/participantAttributes",
    promotionParticipants = "promotion/participants",
    promotionRoi = "promotion/roi",
    campaigns = "/campaigns",
    analytics = "/analytics",
    masterDataImportConfig = "/configuration/data-import/master-data",
    promotionImportConfig = "/configuration/data-import/promotion",
    forecastDemandImportConfig = "/configuration/data-import/forecast-demand",
    promotionConfig = "/configuration/promotion-configuration",
    userPermissionsConfig = "/configuration/user-permissions",
    logFilesList = "/configuration/log-files",
    pocInputsDesign = "/poc/inputs-design"
}